#!/bin/bash

PROJECT_ROOT=$(realpath $(dirname $0)/../.. )
CMAKE_WORK_DIR=${PROJECT_ROOT}/build
NUMBER_JOBS=8

[ ! -d $CMAKE_WORK_DIR ] && mkdir ${CMAKE_WORK_DIR}
cd ${CMAKE_WORK_DIR}
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ${PROJECT_ROOT} -G Ninja && ninja -j ${NUMBER_JOBS}
ctest
